### ISSUE TITLE
Disable security for spring boot management endpoints

### ISSUE THREAD

**Issue by igorkaroza** [spring-cloud/spring-cloud-dataflow#1527]
I'm trying to disable security for spring boot management endpoints on local SCDF server 1.2.1.RELEASE. Here is my application.yml:
```
server:
  port: 9393
  
security:
  basic:
    enabled: true
    
management:
  contextPath: /management
  port: 9392
  security:  
    enabled: false
    
spring:
  cloud:
    dataflow:
      security:
        authentication:
          file:
            enabled: true                                                   
            users:                                                        
              admin: secret, ROLE_VIEW, ROLE_CREATE, ROLE_MANAGE
```

Even though ` management.security.enabled=false`, management endpoints remain secured with basic authentication and I am getting response:

```
{
  "timestamp": "2017-06-07T12:57:14.713Z",
  "status": 401,
  "error": "Unauthorized",
  "message": "Full authentication is required to access this resource",
  "path": "/management/metrics"
}
```
