### ISSUE TITLE
Properties passed to `stream skipper update` should be same format as non-skipper case

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1750]
Currently we update the stream by passing in a 'skipper' style YAML document
```
stream skipper update ticktock --yamlFile log-level-change.yml
```
Where `log-level-change.yml` is
```
log:
  version: 1.1.1.RELEASE
  spec:
    applicationProperties:
      server.port: 9999
      endpoints.sensitive: false
      log.level: ERROR
    deploymentProperties:
      memory: 4096m
```
We should not make the user aware of this underlying format since they are used to a specific way to set application and deployer properties when deploying a stream without skipper..

```
stream deploy ticktock --properties="app.time.trigger.delay=5,deployer.time.memory=2G"
```

We should not require the user to create a 'skipper' flavored yaml file to specify the app or deployment properties.  A more SCDF centric YAML file format for this would look like
```
stream skipper update ticktock --yamlFile log-level-change.yml
```
Where `log-level-change.yml` is
```
app:
  log:
    version: 1.1.1.RELEASE
    server.port: 9999
    endpoints.sensitive: false
    log.level: ERROR
deployer
  log:
     memory: 4096m
```

The translation to pass these properties to skipper using `log.spec.applicationProperties` format will need to be implemented.  Note, that `version` isn't really an application property , maybe it needs to be handled differently.
```
versions:
  log: 1.1.1.RELEASE
app:
  log:
    server.port: 9999
    endpoints.sensitive: false
    log.level: ERROR
deployer:
  log:
     memory: 4096m
```
