### ISSUE TITLE
Deployment Properties from YAML file that are not strings get dropped.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1808]
The method `DeploymentPropertiesUtils.convert(props)` removes all properties that are not strings.

Therefore, a yaml file with the contents

```
version:
  log: 1.2.0.RELEASE
app:
  log:
    server.port: 9002
    endpoints.sensititve: false
    log.level: ERROR

```
will not have the `server.port` nor the `endpoints.sensitive` property passed as deployment properties, and will 'silently' be dropped.

Not sure why this was done, but we should just convert to string values everywhere.
