### ISSUE TITLE
Resurface the checksum addition to AboutController

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1829]
As a developer, I'd like to recommit the addition of checksum to `AboutController` that was merged via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/49de3abaffd7566aa72bb5a99d9d8dfdfc4f2831.

This commit https://github.com/spring-cloud/spring-cloud-dataflow/commit/b4c3835c77b88d2d04df49c019a08413ef556747 removed it due to the issues encountered at the time of 1.3 M3 release.

**Comment by jvalkeal** [comment]
I don't fully understand why we need all this and why PR were reverted. Having said that and looking what original PR does, I don't think this is something we want to put into dataflow itself. It is way too opinionated what we do and how we build our package for snapshots/milestones/releases. Docs try to explain if user is behind firewall, etc, but everything in this just feels so wrong.

**Comment by sabbyanandan** [comment]
It is required because the SCDF-tile's CLI plugin is automating the download of the compatible shell and SSO login. They would want to make sure the downloaded bits can be verified and that it is not malicious binary.

It was reverted for the 1.3 M3 release. The addition to the controller was causing `/about` tab to break. It has been addressed now via: spring-cloud/spring-cloud-dataflow-ui#558.

**Comment by jvalkeal** [comment]
What I'd propose is having properties like:
```
spring:
  cloud:
    dataflow:
      version-info:
        dependencies:
          dashboard-url: <either raw url pointing to sha file>  	
          dashboard: <or raw sha or whatever other checksum>  	
```
`spring.cloud.dataflow.version-info.dependencies` would be a simple map with key pointing to arbitrary dependency and its value either to sha/checksum itself, or url pointing to sha http resource itself.

Then `/about` would simply list these dependencies. On default we'd simply keep these empty as in normal server impls build we don't need any of this. Also hitting url's will make `AboutController` slow.

As tile will anyway re-package server, they can then manually add configuration about these deps and sha's in ways what is suitable for running server in a tile. This will then give them full flexibility to add any deps. Maybe tile guys want to have their own static server somewhere where they can place and keep sha's securely as I'd assume that is better than fetching something from our repo or central.

**Comment by jvalkeal** [comment]
ups, accidentally closed this.

**Comment by glyn** [comment]
@jvalkeal the required JSON format which was previously agreed is described in [this comment](https://github.com/spring-cloud/spring-cloud-dataflow/issues/1779#issuecomment-345295607) in the issue #1799. I don't feel too strongly how this is implemented, but please note that it must be possible to return _both_ SHA-1 and SHA-256 checksums when SHA-256 is eventually available.

Also please note that the previous implementation was supposed to provide default values for the download URL and SHA-1 checksum so that the tile consuming the dataflow server would not need to configure these values in the usual case.

**Comment by jvalkeal** [comment]
@glyn Point was that you would would provide those values as you repackage server and can add your own application.yml. It's not feasible that we add anything there on default because it will make page slower and it's not needed for other than tile. We should never rely anything on artifactory or maven as we don't fully control those(aka why we don't have sha256).

I don't see no difference embedding raw checksums in an server vs. embedding url to fetch checksums as both can be faked(if one would be about to get a compromised jar). At least with this you could calculate your own sha256. In a perfect world, sha's you show in pivnet would be a source or truth.

**Comment by glyn** [comment]
@jvalkeal to avoid revisiting all the discussion behind https://github.com/spring-cloud/spring-cloud-dataflow/commit/49de3abaffd7566aa72bb5a99d9d8dfdfc4f2831, I've sent you some information on slack and in a Google doc that will hopefully provide more context.

On the specific issues you raise:
* the dataflow server should be the source of truth as to which is the latest shell version it supports - the tile has no better way to tell than by asking the dataflow server.
* there should be negligible performance impact in returning two or three more _build-time constant_ strings in the JSON payload of `/about`.
* we previously considering using a checksum URL instead of a checksum value. However, a checksum value is more convenient than a checksum URL to users of the `/about` endpoint, so why not deference the checksum URL at dataflow server build time?

**Comment by jvalkeal** [comment]
To overcome regression issue in old PR which added 4 different dependencies, which then effectively caused 4 http requests against artifactory order to find sha1 files, I'm proposing new config model.
```
spring:
  cloud:
    dataflow:
      version-info:
        dependency:
          enabled: false
        dependencies:
          spring-cloud-dataflow-shell:
            name: Spring Cloud Data Flow Shell
            version: 1.3.0.RELEASE
            url: "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.3.0.RELEASE/spring-cloud-dataflow-shell-1.3.0.RELEASE.jar"
            checksum-sha1: 596d0d1cb1c2d44dd8586de956893ca77d265e9"
            checksum-sha1-url: "http://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.3.0.RELEASE/spring-cloud-dataflow-shell-1.3.0.RELEASE.pom.sha1"
            checksum-sha256: 154c1debfe8a65b1e2a3892d6e230bfd1c1ac999ce51b27ba9f46868ae4fe849
            checksum-sha256-url: "http://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.3.0.RELEASE/spring-cloud-dataflow-shell-1.3.0.RELEASE.pom.sha256"
```
In a nutshell:

1. we'd have a new property `spring.cloud.dataflow.version-info.dependency.enabled=false` which disables whole functionality on default, effectively removing any regression concerns. Then a server which gets re-packaged in tile can set that property to `true` and they get this json payload depending what is actually in a configuration.
2. `spring.cloud.dataflow.version-info.dependencies` would simply be a map pointing to other options per dependency.
3. We'd explicitely define `url` pointing to physical artifact and `name` and `version` as those seem to be present in json.
4. We'd add options `checksum-sha1`, `checksum-sha1-url` and same for `sha256`. If raw checksum is defined with `checksum-sha1`, we'd use that and fall back to fetching checksum from `checksum-sha1-url`.

These would allow us to define one default for `spring-cloud-dataflow-shell` still pointing to sha1 in artifactory. If user is behind a firewall, then they have option to change this `checksum-sha1-url` pointing to local http resource or hardcode `checksum-sha1` which would not cause any extra hops to external http endpoints.

I believe this will keep everyone happy and provides enough flexibility to change things without modifying dataflow core.

1. No regression for other users as it's disabled by default.
2. Tile team only needs to add enabled flag once and then just update dataflow versions if there's no need to change these properties.
3. If tile team needs sha256, and artifactory is not able to provide one in timely fashion, then they can hardcode raw sha256 or its url if needed.
4. If tile team suddenly needs to change url where shell is downloaded, they can do it by changing config without changing checksum properties.
5. If tile team needs a new dependency(other than shell) in a json payload they can just add more configs to that map.
