### ISSUE TITLE
Add support for multiple input/output channels

### ISSUE THREAD

**Issue by rahulbats** [spring-cloud/spring-cloud-dataflow#2331]
my stream takes multiple input channnel.
For instance it takes input from 2 topics and creates a ktable from one and joins it with kstream from other.
Same way in output it does a branch and sends to multiple channels.
How do i get a processor like this to work in dataflow. Since spring-cloud-stream support multiple input and output channels, why does dataflow not support it ?

**Comment by sabbyanandan** [comment]
Hi, @rahulbats. Can you share a sample of the Application? I'd like to review your channel configurations and the corresponding destination mapping. 

SCDF automates the channel/destination naming for applications in the pipeline. The naming convention typically follow the `<stream-name>.<producer-app-name>` pattern. If you have a custom name or a descriptive channel naming-conventions in the App, SCDF won't be able to use them as-is. 

We re exploring options to support this type of orchestration more natively in SCDF, but before we get into the details, it'd be better to confirm your Application configs and what you see as current runtime behavior.

**Comment by rahulbats** [comment]
Hi,
i am using the app to join a kstream and ktable created from 2 kafka topics 

i am using a custom binding like this 

```
public interface SubscriptionsNotificationsBindings {
	@Input("events")
	KStream<?, ?> events();
	
	@Input("subscriptions")
	KStream<?, ?> subscriptions();
	
	
	@Output("emails")
	KStream<?, ?> emails();
	
	
	@Output("texts")
	KStream<?, ?> texts();
	
}


```
and then my processor looks like this 
```
@EnableBinding(SubscriptionsNotificationsBindings.class)
public class EventToNotificationGenerator {
	
	@StreamListener
	@SendTo({"emails","texts"})
	public KStream<String, String>[]  process(@Input("events") KStream<String, String> events,
						@Input("subscriptions") KStream<String, String> subscriptions
			) {
}


```

my application yml has bindings like this 

```
spring.cloud.stream.bindings.subscriptions:
 destination: com.bnsf.snf.subscriptions
 consumer:
  headerMode: raw  
spring.cloud.stream.bindings.events:
 destination: com.bnsf.snf.events
 consumer:
  headerMode: raw
spring.cloud.stream.bindings.texts:
 destination: com.bnsf.snf.texts
 producer:
  use-native-encoding: true
spring.cloud.stream.bindings.emails:
 destination: com.bnsf.snf.emails
 producer:
  use-native-encoding: true  
```


this is how i was able to use a multi input multi output processor
