### ISSUE TITLE
Boot2 - handle security changes

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2382]
`spring-security` have changes for some configurers and class locations.

Child of #914

**Comment by jvalkeal** [comment]
It looks like we're getting error:
```
2018-09-03 16:14:31.990  WARN 17209 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.security.servlet.SpringBootWebSecurityConfiguration$DefaultConfigurerAdapter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor<?>' available
```
which might be some kind of ordering issue as boot should use `@EnableWebSecurity`. We also tweak things from common security which explains why things wont blow up if I exclude `org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration`.

Boot's security auto-config were heavily re-written so this may not be a surprise.

**Comment by jvalkeal** [comment]
Looks like we need to think about how to use passwords as there is not a format change. For tests I'm now just changing to have `noop` id, something like:
```
spring:
  cloud:
    dataflow:
      security:
        authentication:
          file:
            enabled: true
            users:
              bob: "{noop}bobspassword, ROLE_VIEW"
              alice: "{noop}alicepwd, ROLE_MANAGE"
              cartman: "{noop}cartmanpwd, ROLE_CREATE"
              fulluser: "{noop}fullpassword, ROLE_VIEW, ROLE_MANAGE, ROLE_CREATE"
```
