### ISSUE TITLE
Test stream/task deployments against multiple cf/k8s platform backends

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2852]
As a developer, I'd like to define multiple cf/k8s platform backends in SCDF (task config) +Skipper (stream config), so I can create, deploy or launch stream and tasks against different platforms from the Shell/UI.

**Acceptance:**
- Define 2 CF accounts (perhaps also in different pas environments)
- Define 2 K8s accounts (even on different K8s clusters)
- Deploy and Launch Streams and Tasks against different CF/K8s accounts
- Verify the deployment and launches were successful
- Verify the status and audit-history is correctly recorded

**Comment by sabbyanandan** [comment]
Here are the running notes of my experiment so far:

- With latest from `master`, I've SCDF, Skipper, Kafka and other components set up on K8s.
- In `server-config-kafka.yaml`, I have had to make 2 changes. 
  - adjust `datasource` section with a common datasource credentials
  - add 4 platform definitions (2 for cf and 2 for k8s - see below)
```
          task:
            platform:
              kubernetes:
                accounts:
                  sabbydev:
                    fabric8:
                      namespace: sabbydev
                    limits:
                      memory: 1048Mi
                  sabbyqa:
                    fabric8:
                      namespace: sabbyqa
                    limits:
                      memory: 1024Mi
                      cpu: 500m
              cloudfoundry:
                accounts:
                  sozadev:
                    connection:
                      url: 
                      org: sabby
                      space: test
                      domain: 
                      username: 
                      password: 
                      skipSslValidation: true
                    deployment:
                      services: rabbit,mysqlcups
                  sozaqa:
                    connection:
                      url: 
                      org: sabby20
                      space: sabby20
                      domain: 
                      username: 
                      password: 
                      skipSslValidation: true
                    deployment:
                      services: rabbit,mysqlcups
```
- With the above, I've 4 platforms with the name "sabbydev" and "sabbyqa" for K8s; "sozadev" and "sozaqa" for CF. The biggest challenge to get this working is the "namespace" configuration for K8s-deployer. It turns out, we _only_ take the `fabric8.namespace` property into account and the top-level `namespace` property never takes precedence, even if it is provided. We will have to revisit this in K8s-deployer.
- I can now use any of the 4 platforms from SCDF to launch Tasks, and all of the Tasks + SCDF share the same datasource, too. Everything works! 😄 

Miscellaneous:
1) The K8s-deployment of SCDF doesn't need to include [bidner properties to Tasks](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-config-kafka.yaml#L28). It can be removed. 
2) In `server-deployment.yaml`, I've had to remove `KUBERNETES_NAMESPACE` since the deployer [automatically](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java#L124) sets it to `default` if not overridden; besides that, we will have to define the namespace more explicitly for each of the K8s-platforms anyway.
3) We need to understand how "datasource" credentials from `server-config-kafka.yaml` (i.e., `application.yaml` section in this file) is automatically also propagated over to all the Task applications. If my understanding is correct, what we see in this file (i.e., "datasource") should only be used by SCDF, and not supplied to the Apps that it deploys.
