### ISSUE TITLE
Add support to configure Security Context for the deployed streams/tasks

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3313]
**Description:**
I need config scdf2 skipper , scdf and app pods to run without root and no write into filesystem pod . 

**Release versions:**
There is an API (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-server-meta-retrieving) to gather SCDF's system information, including the dependent projects and the associated versions. Alternatively, you can capture this information from the Dashboard's About tab (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#dashboard). Please be sure to include the copied JSON in the bug report.

**Custom apps:**
task show log with date time
skipper server config:
```
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:            
                    namespace: default
                    deploymentServiceAccountName: scdf2-server-data-flow
                    securityContext:
                      runAsUser: 2000
                      allowPrivilegeEscalation: false
                    limits:
```
**Steps to reproduce:**
I made changes into config yamls 
```
data: application.yaml: |- spring: cloud: skipper: server: platform: kubernetes: accounts: default:
namespace: default deploymentServiceAccountName: scdf2-server-data-flow securityContext: runAsUser: 2000 allowPrivilegeEscalation: false limits: Colla
```

And scdf start runs with user "2000", (there is a problem with writeable local maven repo, fixed with a pvc nfs)...
But, the app pods always starts as root user, no 2000 users. I've change skipper-config with securitycontext, .. any clues?
