### ISSUE TITLE
How to add login validation to spring-cloud-dataflow-server

### ISSUE THREAD

**Issue by jiangzhikele** [spring-cloud/spring-cloud-dataflow#3314]
![image](https://user-images.githubusercontent.com/38905258/60800712-3ce92200-a1a8-11e9-9c01-d1171b1e755d.png)
I installed it. 
now 
No login is required to display the page directly.
How to add login validation to spring-cloud-dataflow-server
thanks

**Comment by jiangzhikele** [comment]
I forgot to mention that I used k8s deployment

**Comment by ilayaperumalg** [comment]
Hi @jiangzhikele,

Spring Cloud Data Flow supports `OAuth2` and `OpenID connect` for authentication and authorization. 

For OAuth, you can use the following properties to configure SCDF server based on your OAuth2 provider:

```
security:
  oauth2:
    client:
      client-id: myclient                                             
      client-secret: mysecret
      access-token-uri: xxx
      user-authorization-uri: xxx
    resource:
      user-info-uri: xxxx                         
      token-info-uri: xxx
```
