### ISSUE TITLE
Kubernetes : Passing secret via enviroment variables

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3372]
**Problem description:**
Our tasks need to access kubernetes secrets when deployed.

Most of the time I use secrets injected as environement variable so a spring boot application can directly use them without knowing where it comes from.

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

Inside a pod definition here how it works :
```
    spec:
      containers:
      - name: xxx
        image: xxx
        ports:
        - containerPort: xxx
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: db_username
```

Right now, we can already pass environement variables. 
Ex: for SPRING_PROFILES_ACTIVE it is working great : 
```
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                environmentVariables: 'SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}'
    scheduler:
      kubernetes:
        environmentVariables: 'SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}'     
```

However, we cannot define env variables from secrets.

**Solution description:**
It would be great/required to be able to define that kind of env variables.

A possible solution would be to define them as Json or any other way inside properties :
```
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                environmentVariablesFrom: '[
                  {"name" : "SPRING_DATASOURCE_USERNAME", "valueFrom": { "secretKeyRef" : { "key": "db_username", "name": "database-secret"} } },
                  {"name" : "SPRING_DATASOURCE_PASSWORD", "valueFrom": { "secretKeyRef" : { "key": "db_password", "name": "database-secret"} } }
                  ]'
    scheduler:
      kubernetes:
        environmentVariablesFrom: '[
          {"name" : "SPRING_DATASOURCE_USERNAME", "valueFrom": { "secretKeyRef" : { "key": "db_username", "name": "database-secret"} } },
          {"name" : "SPRING_DATASOURCE_PASSWORD", "valueFrom": { "secretKeyRef" : { "key": "db_password", "name": "database-secret"} } }
          ]'
```

Then update org.springframework.cloud.deployer.spi.kubernetes.DefaultContainerFactory and org.springframework.cloud.scheduler.spi.kubernetes.ContainerCreator to be able to use these env variables. 
(It's a shame that container factories are not the same on both deployer and scheduler, moreover, if a bean could be overrided for containerFactory in the deployer configuration, containercreator is not a bean in the scheduler !)

**Description of alternatives:**
I had to replace org.springframework.cloud.deployer.spi.kubernetes.KubernetesDeployerProperties and org.springframework.cloud.scheduler.spi.kubernetes.KubernetesSchedulerProperties to support these new properties.
Then I had to replace org.springframework.cloud.deployer.spi.kubernetes.DefaultContainerFactory and org.springframework.cloud.scheduler.spi.kubernetes.ContainerCreator to be able to use these new env variables. 

Implementation is straightforward because Json is just fetched from modified properties and directly deserialized to io.fabric8.kubernetes.api.model.EnvVar :

```java
  private static List<EnvVar> getTaskEnvironmentVariablesFrom(
      ScheduleRequest request,
      KubernetesSchedulerProperties kubernetesSchedulerProperties
  ) {
    ObjectMapper objectMapper = new ObjectMapper();
    List<EnvVar> envVars = new ArrayList<>();

    String environmentVariableFrom = kubernetesSchedulerProperties.getEnvironmentVariablesFrom();
    if(isNotBlank(environmentVariableFrom)) {
      try {
        envVars.addAll(objectMapper.readValue(environmentVariableFrom, new TypeReference<List<EnvVar>>() {
        }));
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }


    String taskEnvironmentVariablesFrom = request.getSchedulerProperties().get(KubernetesSchedulerProperties.KUBERNETES_SCHEDULER_PROPERTIES + ".environmentVariablesFrom");
    if(isNotBlank(taskEnvironmentVariablesFrom)) {
      try {
        envVars.addAll(objectMapper.readValue(taskEnvironmentVariablesFrom, new TypeReference<List<EnvVar>>() {
        }));
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }
    return envVars;
  }

```
