### ISSUE TITLE
spring data flow server k8s lifecycle properties.

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3478]
**Problem description:**  
Allow deployment pods using lifecycle properties.

We are getting some trouble hangling request from http client side, specially using bosh and grpc protocols.

"Client-side" requesters to our http source app are sending reports about losting processing request and they  get many requests  in "undefined" status or losted after our "ordered" shutdown, where they are connected to our http source app.

We have observed that there is not a "secure" shutdown from http-source app (using undertow server inside), and we are looking into undertow forums and we cannot get any report about lost request in a shutdown process .. all infos say that undertow shutdown "wait" to finish until processing all requests and not allow new connection ... but we check that it is not always true ...

We think that some request are still processed into k8s workflow and they are losted where they are delivered to our "undertow server" into the pod into a shutdown process.

We think that we got a problem preventing broken connections during pod shutdown

**Solution description:**
Looking for info, google, we found, 

``
https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
``

Then, TL DR: 
We need to exec a preStop process to "wait" the finish for async process into k8s stopping process.

We  need to deploy pods applying lifecycle k8s exec
````
 lifecycle:                   
      preStop:                   
        exec:                    
          command:               
          - sh
          - -c
          - "sleep 15"
 ````
