### ISSUE TITLE
How to map the SCDF role mappings in keycloak 

### ISSUE THREAD

**Issue by aarti-stack** [spring-cloud/spring-cloud-dataflow#3488]
I am using Keycloak as a access manager for the client Spring Cloud Data Flow .I have integrated with Open LDAP through User Federation for the users and have mapped LDAP groups as roles in the Keycloak.

All these scopes are mapped as groups in Open LDAP and I have created a role-ldap-mapper for it.Below are the list of roles

Scope dataflow.create maps to the CREATE role

Scope dataflow.deploy maps to the DEPLOY role

Scope dataflow.destroy maps to the DESTROY role

Scope dataflow.manage maps to the MANAGE role

Scope dataflow.modify maps to the MODIFY role

Scope dataflow.schedule maps to the SCHEDULE role

Scope dataflow.view maps to the VIEW role

I am able to authenticate the user but I get Roles missing error while I land on the Spring cloud data flow dashboard page.

**Comment by jvalkeal** [comment]
You should show your dataflow configuration and logs what happens during authentication. If I'd need to take a guess, authorities extractor doesn't work which is setup here:

https://github.com/spring-cloud/spring-cloud-common-security-config/blob/f3ac6416ef805e9c1b22e3e8ce24cc43184f4eb5/spring-cloud-common-security-config-web/src/main/java/org/springframework/cloud/common/security/OAuthSecurityConfiguration.java#L185-L191

Logs should for example show if it's trying to default giving all roles, i.e.:
```
2019-09-10 05:16:16.718  INFO 1 --- [nio-9393-exec-6] o.s.c.c.s.s.DefaultAuthoritiesExtractor  : Adding ALL roles VIEW,SCHEDULE,MANAGE,DESTROY,CREATE,DEPLOY,MODIFY to user {user_id=add56ca9-0501-4f4d-9768-c9bd08ee0f25, user_name=janne, email=janne, email_verified=true, previous_logon_time=null, name=, sub=add56ca9-0501-4f4d-9768-c9bd08ee0f25}
```
or if something goes wrong with `ExternalOauth2ResourceAuthoritiesExtractor`. We're not that familiar with keycloak but we really need more info from you.

**Comment by jvalkeal** [comment]
I quickly played with keycloak with this config;
```
spring:
  cloud:
    dataflow:
      security:
        authorization:
          map-oauth-scopes: true
          role-mappings:
            ROLE_CREATE: dataflow.create                           
            ROLE_DEPLOY: dataflow.deploy
            ROLE_DESTROY: dataflow.destoy
            ROLE_MANAGE: dataflow.manage
            ROLE_MODIFY: dataflow.modify
            ROLE_SCHEDULE: dataflow.schedule
            ROLE_VIEW: dataflow.view
security:
  oauth2:
    client:
      client-id: dataflow-service
      client-secret: 87f066f0-53cc-4938-8077-148e0b4a9619
      scope: openid
      access-token-uri: http://localhost:8080/auth/realms/dataflow/protocol/openid-connect/token
      user-authorization-uri: http://localhost:8080/auth/realms/dataflow/protocol/openid-connect/auth
    resource:
      user-info-uri: http://localhost:8080/auth/realms/dataflow/protocol/openid-connect/userinfo
      token-info-uri: http://localhost:8080/auth/realms/dataflow/protocol/openid-connect/token/introspect
```
On a keycload side I didn't do anything else rather than created `dataflow-service` client, a user and assigned one default `dataflow.view` client scope.

Then I was able to login and not getting that missing role error. I think you just need to find a correct keycloak setup so that needed oauth scopes are returned for logged in user.

**Comment by eskuai** [comment]
Hi @aarti-stack 

Could you copy and paste debug log info from scdf and keycloak here?
and can you detail about what spi are you using(k8s)?

It could very usefull if you can attach a screen capture with networking request from browser( see http codes, loops, failed to redirect, failed to load big file nodejs, failed to check cacerts, etc..)

**Comment by eskuai** [comment]
Hi @jvalkeal,

Have you a keycloak pod  on k8s running applying "scope: openid"  from config into scdf and skipper?

Great, because, like from uaa server, on my k8s, i must to disable it ... and it is working ... incluing removing always mapping between failed starts (something into database is not fully removed).

You could read my "adventure" to make uaa working with scdf2 at stackoverflow ... 
``
https://stackoverflow.com/questions/57376292/scdf2-uaa-request-failed-redirect-to-dashboard-from-login
``
And you could not apply scope openid because keycloak  as uaa, only if scope is omitted or null, all scopes will be assigned to the client, and no needed confirmation for third party permission ... if not, openid is appliyed and it fails... no mapping anything...

Coud you confirm that you environment is working with the logout process?

But i cannot make run ( nor keycloack neither uaa)  using scdf2, but, this is another story.

**Comment by aarti-stack** [comment]
@jvalkeal  : Could you please mention which keycloak version setup. Did you use the Client Scopes option to as the Oauth scope to the user??

**Comment by jvalkeal** [comment]
I used latest keycloak(7.0.0) and dataflow 2.3.0 snapshots.

1. Created a role `xxx` (more about that later).
![kc-roles](https://user-images.githubusercontent.com/50398/64669001-7ec46c00-d468-11e9-8f59-1821de39b1e2.png)

2. Created `dataflow-service` client, did change `access type`, `service accounts enabled`, `authorization enabled`, `root uri` and `valid rediret uris`.

![kc-client](https://user-images.githubusercontent.com/50398/64668994-7b30e500-d468-11e9-840b-f2967951cd99.png)

3. Created client scopes `dataflow.view` and `dataflow.create` and assigned role `xxx` to `dataflow.create`.

![kc-clientscopes](https://user-images.githubusercontent.com/50398/64669006-81bf5c80-d468-11e9-974e-8a18395da3ba.png)

4. Added those 2 scopes as `Assigned Default Client Scopes`

![kc-client-default-scopes](https://user-images.githubusercontent.com/50398/64669013-8552e380-d468-11e9-9cef-d4527ada4cc9.png)

5. Created users `guest` and `janne` and gave `janne` a `xxx` role.

![kc-user-janne](https://user-images.githubusercontent.com/50398/64669017-87b53d80-d468-11e9-9fd9-4aa3e12db388.png)

It looks like even if scope is added to a client with `Assigned Default Client Scopes`, it's not assigned if user
don't have matching `xxx` role. Thus,

Logging if with `guest` gives just `ROLE_VIEW`:
```
o.s.c.c.s.s.DefaultAuthoritiesExtractor  : Adding roles ROLE_VIEW to user {sub=dc0144fe-714c-46f4-aaa4-a4a45187e24f, email_verified=false, preferred_username=guest}
```

Logging if with `janne` gives `ROLE_VIEW` and `ROLE_CREATE`:
```
o.s.c.c.s.s.DefaultAuthoritiesExtractor  : Adding roles ROLE_VIEW,ROLE_CREATE to user {sub=1eaa6185-c394-4990-945c-10596fbf1ccf, email_verified=false, name=Janne Valkealahti, preferred_username=janne, given_name=Janne, family_name=Valkealahti}
```

**Comment by jvalkeal** [comment]
I didn't try any ldap integration but I'd assume it would be just mapping users to a keycloak roles(role mapping on a dataflow side is a different thing). Also there's probably different ways to do things with keycloak and as I'm a complete n00b with it this was just a quick way to get something working.

**Comment by eskuai** [comment]
@jvalkeal 

what about /logout?

**Comment by eskuai** [comment]
Hi @jvalkeal,

Sorry, I didn't try to hijack differents issues, I  am trying to get the common context to write more precise and usefull issues.

I think that it is more easy to do users and mapping profiles using uaa than keyclock, because using keycloack we cannot forget apply "roles" from it, and it is not needed into the process applying uaa.

Applying uaa, it is always the same process, using uaac client:

1) using the uaa_admin user, create a sesion and get a token
2) create the user you need
`` uaac user add admin -p password --emails admin@mk.com `` 
3) create a group as you need, mapping to tag/role from scdf side
`` uaac group add "dataflow.view``
4) add the user to a new group  (then the user is grant to this role/tab scdf side
``  uaac member add dataflow.view admin `` 
5) repeat as you need 
`` uaac member add  dataflow.manage admin``
6) create dataflowclient (scdf side)
`` uaac client add dataflow \
   --name dataflow \
   --scope  "cloud_controller.read password.write scim.userids dataflow.view dataflow.manage cloud_controller.write dataflow.destroy openid dataflow.create dataflow.schedule dataflow.deploy dataflow.modify" \
   --authorized_grant_types password,authorization_code,client_credentials,refresh_token \
   --authorities uaa.resource \
   --redirect_uri http://scdf2-data-flow-server:8844/login  \
   --autoapprove openid \
   --secret dataflow
`` 
7) Check the relation it is ok,  your uaa user is related to the 
``  curl -v -d"username=admin&password=password&client_id=dataflow&grant_type=client_credentials" -u "dataflow:dataflow" https://uaa-service:8443/oauth/token
`` 

Is it could be possible the scdf starts applying multipe uaa clients? today is only one.
Then, create many users, mapping with differents groups/roles, scdf, and it it works.
It could be better thaat scdf can user a list of "uaa clients".

Ok, I'll open a new issue about /logut, but i dont know it is the rigth moment
It is a hard work to be sure that the uaa sessions token is closed and the user can "login" into a right way

Tx,

**Comment by jvalkeal** [comment]
Well I mostly meant myself about moving outside from keycloak ;)

**Comment by jvalkeal** [comment]
I've tried to avoid using `uaac` client in favour if configuring everything in `uaa.yml` so that I could eventually have ready-made image what we could use for testing. Afaik, you can almost do all basic things in yml what people usually add via `uaac`.

**Comment by aarti-stack** [comment]
Hi @eskuai  I had used uaa server for the scdf and it worked fine with me but I wanted to try with keycloak.

Hi @jvalkeal  : I was using the  old image of keycloak which did not had client scopes option.New image had certain issues while keycloak server started.However I have resolved the image error and able to integrate keycloak with scdf with no roles missing error.Thank you for your input.

**Comment by eskuai** [comment]
@hi aarti-stack

I got the same problem now

I think that I follow the instructions but it fails by missing roles

Can you post your keycloak config?

tx

**Comment by pptllakshitha** [comment]
HI @jvalkeal,
when I add the following attribute to my yml file in IntelliJ those all are getting highlighted I added some dependencies also but nothing solve my problems .could please help me.

![error-SCDF](https://user-images.githubusercontent.com/73877677/104201826-29c7aa00-5450-11eb-9338-6e0da13e031d.PNG)

**Comment by eskuai** [comment]
Hi @pptllakshitha 

Check https://github.com/jvalkeal/randomstuff/tree/master/dataflow-keycloak very carefully and it works ...

Double check to json definition, skipper side and scdf side ... i dont know why, but if yaml gets some tree-tag configurations not valid ... no issue is warning ...  

I dont know what kc versiones is .. another warn, lastest kc changed configurations windows and "areas" , but the config process is the same ...

Boot scdf and skipper at debug level ... check and check json definition and follow previos link ...

Good luck

**Comment by shehanab** [comment]
I'm facing the same issue with exactly the same configuration.


http://localhost:9393/dashboard takes me to http://localhost:9393/login selection of client name takes me to the following link with my SSO login page...

http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/auth?response_type=code&client_id=ABATCH&scope=openid%20dataflow.view%20dataflow.deploy%20dataflow.destroy%20dataflow.manage%20dataflow.modify%20dataflow.schedule%20dataflow.create&state=oGeeBrngd2RI2Wg2XLBlYJKUQtSQycOeN56EtceS_yw%3D&redirect_uri=http://localhost:9393/login/oauth2/code/keycloak&nonce=eVZQyD23xjmnA49e7uN_vjGvsLJQUcX5gUl2GItohQY

Upon login in using SSO login page it requests using the following link...

http://localhost:8567/auth/realms/GetsConnect/login-actions/authenticate?session_code=E6VoTYWMB7k9R5l_W23yY6RixQWfTN8EsaDmPtxOfMk&execution=ca0c2c76-8111-4447-92b3-315cf3222a48&client_id=ABATCH&tab_id=-1rfgFmUOsw

then it attempts to access the following redirect URL specified...

http://localhost:9393/login/oauth2/code/keycloak?state=oGeeBrngd2RI2Wg2XLBlYJKUQtSQycOeN56EtceS_yw%3D&session_state=ff40cd7b-a699-4465-b36a-cea919fa9391&code=2f811454-4855-4def-8732-89b248d4bbba.ff40cd7b-a699-4465-b36a-cea919fa9391.c33a1552-9eda-4069-885e-2bdaed4e5a15

This leads me to http://localhost:9393/login?error page with the following error message

[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: I/O error on POST request for "http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/token": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect


From Keycloak server-side login successful but it does not return the token (code_to_token response) and redirects to the login page. 

Configs are as follows...

```
spring:
  cloud:
    dataflow:
      security:
        authorization:
          provider-role-mappings:
            keycloak:
              map-oauth-scopes: true
              role-mappings:
                ROLE_VIEW: dataflow.view
                ROLE_CREATE: dataflow.create
                ROLE_MANAGE: dataflow.manage
                ROLE_DEPLOY: dataflow.create
                ROLE_DESTROY: dataflow.create
                ROLE_MODIFY: dataflow.create
                ROLE_SCHEDULE: dataflow.create
  security:
    oauth2:
      client:
        registration:
          keycloak:
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-id: ABATCH
            client-name: ABATCH
            client-secret: a0f442f5-8c58-4220-9b48-4174476ba57a
            scope:
              - openid
              - dataflow.view
              - dataflow.deploy
              - dataflow.destroy
              - dataflow.manage
              - dataflow.modify
              - dataflow.schedule
              - dataflow.create
        provider:
          keycloak:
            jwk-set-uri: http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/certs
            token-uri: http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/token
            user-info-uri: http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/userinfo
            user-name-attribute: user_name
            authorization-uri: http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/auth
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8567/auth/realms/GetsConnect/protocol/openid-connect/token/introspect
          client-id: ABATCH
          client-secret: a0f442f5-8c58-4220-9b48-4174476ba57a
      authorization:
        check-token-access: isAuthenticated()


```

Appreciate If someone could give some tips...  @eskuai @jvalkeal
