### ISSUE TITLE
Kubernetes podAnnotation property is not used

### ISSUE THREAD

**Issue by mihaita-tinta** [spring-cloud/spring-cloud-dataflow#3578]
Hello.
According to the documentation we can create some pod annotations using a property like the one below:
> deployer.http.kubernetes.pod-annotations=prometheus.io/path:/actuator/prometheus

Unfortunately I can't see this annotation in the http deployment automatically created by the kubernetes deployer nor in the pod spec
Deployment:

```yaml
spec:
  ...
 template:
    metadata:
      creationTimestamp: null
#   annotations:                                                       
#        prometheus.io/path:/actuator/prometheus -------------> missing
      labels:
        role: spring-app
        spring-app-id: test-http-v5
        spring-deployment-id: test-http-v5
        spring-group-id: test
```

If I manually add this here, I get the desired behaviour. (Prometheus can use the right path to get metrics) Am I missing something or is this really a bug?
