### ISSUE TITLE
Service account and cluster role binding are mismatched for prometheus and prometheus-proxy

### ISSUE THREAD

**Issue by echang0929** [spring-cloud/spring-cloud-dataflow#3618]
Both cluster role binding files for prometheus and prometheus-proxy contain subject name as default. 
prometheus-clusterrolebinding.yaml:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus
  labels:
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```

prometheus-proxy-clusterrolebinding.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-proxy
  labels:
    app: prometheus-proxy
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

But their service account names are prometheus and prometheus-proxy respectively in files prometheus-serviceaccount.yaml 
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: default
```
and prometheus-proxy-serviceaccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-proxy
  labels:
    app: prometheus-proxy
  namespace: default
```

Do you think subject names in their cluster role binding files should be changed to prometheus and prometheus-proxy? 

The version I use is Spring Cloud Data Flow 2.3.0.BUILD.SNAPSHOT 
[source codes](https://github.com/spring-cloud/spring-cloud-dataflow)
