### ISSUE TITLE
dashboard environment id label , env logo 

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3623]
**Problem description:**
As I user, I would like to know what scdf dashboard I am using ...
Today, all dashboards are the same ui from differents environments ( live vs work etc)

**Solution description:**
It could be to use a "label id dashboard" from scdf yaml config setting a text.
The same process to include a image-png , encoded using base64 as uaa does.

````
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scdf.fullname" . }}-server
  labels:
    app: {{ template "scdf.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.yaml: |-
    management:
      endpoints:
        web:
          base-path: /management
      security:
        roles: MANAGE
      dashboard:		
         envLabeld: play
         envLogo: hhZjk4YWI3MGJlZCIvPiA8L3JkZjpEZXNjcmlwdGlvb
j4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pv/bA
EMACAYGBwYFCAcHBwkJCAoMFA0MCwsMGRITDxQdGh8eHRocHCAkLicgIiwjHBwoN
yksMDE0NDQfJzk9ODI8LjM0Mv/bAEMBCQkJDAsMGA0NGDIhHCEyMjIyMjIyMjIyM
		
````

**Additional context:**
Add any other context or explanation about the feature request here.

![imagen](https://user-images.githubusercontent.com/1777753/68287117-7d877800-0082-11ea-8168-1f1bc602bad2.png)

![imagen](https://user-images.githubusercontent.com/1777753/68288059-09e66a80-0084-11ea-8754-eebe5d6ec20c.png)
