### ISSUE TITLE
on k8s, server loadbalancer, session affinity

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3760]
**Problem description:**
On K8s, as I user, if I deploy scdf replicateset with replica value  5 or 10 instances, I can see that dashboard got a big delay to process operations. Very poor responsive.

Looking into templates, i can see, that by default, the service loadbalancer has not "Session Affinity".

**Solution description:**
I think that it is good idea, to get better responsve from dashboard web ui , to define a simple session affinity, by clientip for example.

```
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 11000
```

**Additional context:**
I've applied, and i can get better responsive from web ui.
