### ISSUE TITLE
on k8s: predictableIP sample failed  name uppercase

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3808]
**Description:**
On k8s, as a user, testing sample info for a lb from url:
https://dataflow.spring.io/docs/resources/faq/#predictableIP
```
kind: Service
apiVersion: v1
metadata:
  name: FOO-lb
  namespace: kafkazone
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    FOOZ: BAR-APP
  type: LoadBalancer
```

**Steps to reproduce:**

A simple deployment, 

$kubectl apply -f .\servicelbtest.yaml

```
The Service "FOO-lb" is invalid: metadata.name: Invalid value: "FOO-lb": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

Minor upgrade, lowercase "foo" .. 

Tx
