### ISSUE TITLE
Pre-configure Docker Hub authentication uri to prevent lookup on SCDF startup

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#3904]
All OOTB SCDF app starters use Docker Hub registry. In order to retrieve the metadata about those apps (such as whitelisted properties),  

SCDF requires access to the container registry (e.g. Docker Hub). 

When the registry access enforces the Docker specific OAuth2 protocol, SCDF the token service URI in order to be able to issue new tokens and access the Docker Hub metadata.  (Note: that this access will only be applied if app metadata is retrieved for app image hold by the Docker Hub.)

If the registry token service uri is not pre-configured, at bootstrap the SCDF will try to resolve it. So to prevent the bootstrap lookup we need to set the: 

```
--spring.cloud.dataflow.container.registry-configurations[default].extra[registryAuthUri]=https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repository}:pull&offline_token=1&client_id=shell
```

or extend via the yaml:

```yaml
default:
 registry-host: registry-1.docker.io
 authorization-type: dockeroauth2
 extra:
    "registryAuthUri": 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repository}:pull&offline_token=1&client_id=shell'
```
