### ISSUE TITLE
Add an "imagePullSecret" property for composedTaskRunner in TaskConfigurationProperties

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#4009]
**Problem description:**
We just added a property for composedTaskRunnerUri in TaskConfigurationProperties. Since this image might be in a private registry it would make sense to have an "imagePullSecret" property for this uri as well.

**Solution description:**
Add an "imagePullSecret" property for composedTaskRunner in TaskConfigurationProperties.

We could restructure the configuration to match:

```
spring:
  cloud:
    dataflow:
      task:
        composedTaskRunner: 
          uri: docker://registry.example.com/spring-cloud-dataflow-composed-task-runner
          imagePullSecret: example-regcred
```

**Description of alternatives:**
It is possible to set "imagePullSecret" for all task apps using:

```
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                imagePullSecret: example-regcred
```

Since CTR is now part of the distribution and separate from any task apps that are registered it is likely that they are in different registries or use different secrets. It would be better to have a specific entry for the secret to use for the CTR image. 

**Additional context:**
