### ISSUE TITLE
Add K8s installation configurations and documentations for Wavefront support

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4016]
As we continue to promote Wavefront integration, we will have to include the deployment YAMLs to provision Wavefront proxy and the related configurations.

This would follow the same steps as Prometheus and Prometheus Proxy configurations..

While we are at it, let's clean up the SCDF config to optionally only enable Prometheus or Wavefront, as opposed to enabling Prometheus by default as we do today.

Specifically,

```
                   prometheus:
                      enabled: true
                      rsocket:
                        enabled: true
                        host: prometheus-proxy
                        port: 7001
```

Once when we have this ready for the disk files, we will have to apply the same in the Helm chart.
