### ISSUE TITLE
Make it possible to register multiple imagePullSecrets

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#4294]
**Problem description:**

Currently we can only specify one imagePullSecret for skipper:

```
spring:
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              default:
                imagePullSecret: my-secret
```

and data flow:

```
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                imagePullSecret: my-secret
```

**Solution description:**

We would need to be able to specify multiple since stream and task apps could be pulled from multiple registries

**Description of alternatives:**

Combining registry auths in single secret - not well supported by Kubernetes tooling.

**Additional context:**

This only applies to Kubernetes deployments AFAICT
