### ISSUE TITLE
java rest client: support for retry connection

### ISSUE THREAD

**Issue by DemianTinkiel** [spring-cloud/spring-cloud-dataflow#4322]
**Problem description:**
At the moment, injecting the rest-client will cause an application to immediately try to connect to SCDF during initialization. SCDF might not be available yet so the client application will fail to start. This is a particular problem in deployments like in docker-compose.

**Solution description:**
Implement a retry mechanism. Something like the [rabbitmq's template](org.springframework.boot.autoconfigure.amqp.RabbitProperties.Retry) approach with retries and growing spacing between retries

**Description of alternatives:**
Lazy init or exclude `DataFlowClientAutoConfiguration` from auto configuration. However these are just kicking the can down the road: connection will be attempted only once

**Additional context:**
N/A

**Comment by sabbyanandan** [comment]
Hi, @DemianTinkiel. Could you share some more specifics as to how you're using the REST-client in the context of SCDF running in a Docker Compose environment? It'd be useful to understand the background, so we can think through this not just for this sandbox-kind deployment, but also when running in platforms like K8s.

**Comment by DemianTinkiel** [comment]
@sabbyanandan  sure. My deployment is
```
  dataflow-server:
    image: spring-cloud-dataflow-server:2.8.0-SNAPSHOT
    expose:
      - "9393"
    environment:
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=PLAINTEXT://broker:9092
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.streams.binder.brokers=PLAINTEXT://broker:9092
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=zookeeper:2181
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.streams.binder.zkNodes=zookeeper:2181
      - spring.cloud.skipper.client.serverUri=http://skipper-server:7577/api
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dataflow
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_DOCKER_NETWORK=foo_default
      - SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_DOCKER_DELETE_CONTAINER_ON_EXIT=true
      - SPRING_CLOUD_DATAFLOW_TASK_COMPOSED_TASK_RUNNER_URI=docker://springcloud/spring-cloud-dataflow-composed-task-runner:2.7.0
      - SPRING_CLOUD_DATAFLOW_SERVER_URI=http://dataflow-server:9393
      - /var/run/docker.sock:/var/run/docker.sock
    volumes:
      - ${HOST_MOUNT_PATH:-.}:${DOCKER_MOUNT_PATH:-/root/scdf}

  skipper-server:
    image: spring-cloud-skipper-server:2.7.0-SNAPSHOT
    expose:
      - "7577"
      - "20000"
    environment:
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_DOCKER_PORTRANGE_LOW=20200
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_DOCKER_PORTRANGE_HIGH=61000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dataflow
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_DOCKER_NETWORK=foo_default
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_DOCKER_DELETE_CONTAINER_ON_EXIT=true
    volumes:
      - ${HOST_MOUNT_PATH:-.}:${DOCKER_MOUNT_PATH:-/root/scdf}
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  myServer:
    image: my.nexus.org/myServer
    depends_on:
      - dataflow-server
  ```
My server has a class that is in charge of communication with SCDF
```
@Component
@Slf4j
public class SpringCloudDataFlowHelper {

    private final DataFlowOperations scdf;

    public SpringCloudDataFlowHelper(DataFlowOperations scdf) {
        this.scdf = scdf;
    }

    public void createStream(String name, Set<String> packages, Map<String, String> parameters) {
        String dsl = packages.stream().collect(Collectors.joining("|"));
        log.debug("creating stream {} as {}", name, dsl);

        Stream.builder(scdf).name(name).definition(dsl).create().deploy(parameters);
    }
}
```

Which is autowired into other services and so on. `packages` matches a collection of custom apps (docker/kafka)
Please let me know if you'd like me to elaborate on something specific
