### ISSUE TITLE
Revisit the use of `type` when defining monitoring system configs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4386]
I have the following config when describing Wavefront, and I am wondering why we need to explicitly include `type` in it.

```
management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
        metric-name: spring.cloud.dataflow.http.server.requests     
    export:
      wavefront:
        enabled: true
        api-token: ${wavefront-api-token}
        uri: https://vmware.wavefront.com
        source: sabby-scdf
      prometheus:
        enabled: true
        rsocket:
          enabled: true
          host: scdf-prometheus-proxy
          port: 7001
spring:
  cloud:
    dataflow:
      metrics.dashboard:
        url: 'https://vmware.wavefront.com'
        type: 'WAVEFRONT'
```

While it might seem useful for when multiple monitoring systems are defined (probably rare cases, though), I don't see this being used in any meaningful ways on the UI since we will only have 1 monitoring-specific button to show. 

Let's revisit the need for it, and if there're ways to avoid and remove extra configs leaking to as user responsibilities.
