### ISSUE TITLE
SCDF server fails to access docker hub behind Netscalar Gateway

### ISSUE THREAD

**Issue by kumarprashant2103** [spring-cloud/spring-cloud-dataflow#4480]
**Description:**
We are getting the below error when we try to execute our applications from private docker registry : Failed to retrieve properties for resource Docker Resource [docker:dtrprod.kbm1.loc/pdev/pdev:test-interactionref-382-46196] because of SunCertPathBuilderException: unable to find valid certification path to requested target
Our docker registry is behind the netscalar gateway.

**Release versions:**

We have been using 2.7.1 version and here is our config file : 

```
Namespace
kub-wcc-ptest
application.yaml
management:
  metrics:
    export:
      prometheus:
        enabled: true
        rsocket:
          enabled: true
          host: prometheus-proxy
          port: 7001
spring:
  cloud:
    dataflow:
      metrics.dashboard:
        url: 'https://grafana:3000'
      container:
        registry-configurations:
          default:
            registry-host: dtrprod.kbm1.loc
            authorization-type: dockeroauth2
            user: <user_name>
            secret: regcred
            extra:
              'registryAuthUri': 'https://dtrprod.kbm1.loc/'              
      task:
        platform:
          kubernetes:
            accounts:
              default:
                imagePullSecret: regcred
                limits:
                  memory: 1024Mi
  datasource:
    url: jdbc:postgresql://vdalpgsqlt001.kbm1.loc:5432/pg_wcc_ptest_spring
    username: <postgresql_user>
    password: <postgresql_password>
    driverClassName: org.postgresql.Driver
    testOnBorrow: true
    validationQuery: "SELECT 1"
	

 - name: SPRING_CLOUD_DEPLOYER_KUBERNETES_IMAGE_PULL_SECRET
          valueFrom:
            secretKeyRef:
              key: .dockerconfigjson
              name: regcred
```
