### ISSUE TITLE
DB password not passed when SPRING_CLOUD_DATAFLOW_TASK_USE_KUBERNETES_SECRETS_FOR_DB_CREDENTIALS is set to true

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#4483]
Hi, 

I have problem in SCDF v.2.7.1 - when SPRING_CLOUD_DATAFLOW_TASK_USE_KUBERNETES_SECRETS_FOR_DB_CREDENTIALS is set to true and I try to run Composed Task I get error:

2021-04-23 12:41:30.729  INFO 1 --- [           main] o.s.c.d.c.ComposedTaskRunner             : Starting ComposedTaskRunner v2.7.1 on hdallreplica-gw0ryo4no3 with PID 1 (/maven/composed-task-runner.jar started by root in /)
2021-04-23 12:41:30.736  INFO 1 --- [           main] o.s.c.d.c.ComposedTaskRunner             : The following profiles are active: production
2021-04-23 12:41:32.356  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-04-23 12:41:32.360  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-04-23 12:41:32.486  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 54ms. Found 0 JPA repository interfaces.
2021-04-23 12:41:33.207  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration' of type [org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration$$EnhancerBySpringCGLIB$$6b4fe84a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-23 12:41:34.254  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-04-23 12:41:35.618 ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:633) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.Driver.makeConnection(Driver.java:465) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.Driver.connect(Driver.java:264) ~[postgresql-42.2.18.jar!/:42.2.18]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) ~[HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) [HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) [HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) [HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) [HikariCP-3.4.5.jar!/:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) [spring-jdbc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) [spring-jdbc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) [spring-jdbc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:324) [spring-jdbc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:133) [spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateDefaultDdlAutoProvider.getDefaultDdlAuto(HibernateDefaultDdlAutoProvider.java:42) [spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.lambda$getVendorProperties$1(HibernateJpaConfiguration.java:130) [spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateSettings.getDdlAuto(HibernateSettings.java:41) ~[spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineDdlAuto(HibernateProperties.java:136) ~[spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.getAdditionalProperties(HibernateProperties.java:102) ~[spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineHibernateProperties(HibernateProperties.java:94) ~[spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.getVendorProperties(HibernateJpaConfiguration.java:132) [spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.entityManagerFactory(JpaBaseConfiguration.java:133) ~[spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]

When I remove SPRING_CLOUD_DATAFLOW_TASK_USE_KUBERNETES_SECRETS_FOR_DB_CREDENTIALS evverything work's ok but password and user db are stored in database.

**Comment by sabbyanandan** [comment]
@szopal: Please share a bit more detail on how SCDF and CTR are configuration and running in your environment. That'd help unpack the specifics and help troubleshoot it.

**Comment by cppwfs** [comment]
This is a feature add for Composed Task Runner.   It would have to add kubernetes specific feature set to retrieve the credentials from secrets.   Currently it expects to get this full suite of credentials from data flow itself.

**Comment by szopal** [comment]
We have connected SCDF with Spring Cloud Config Server where are keep DB credentials. Below Deploymeny and Application configuration:


Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
    spec:
      containers:
        - name: scdf-server
          image: eu.gcr.io/xxxxxxxxxx/spring-cloud-dataflow-server:2.7.1
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: tz-config
              mountPath: /etc/timezone
          ports:
            - containerPort: 9393
          livenessProbe:
            httpGet:
              path: /management/health
              port: 9393
            initialDelaySeconds: 45
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /management/info
              port: 9393
            initialDelaySeconds: 45
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1.0
              memory: 2048Mi
            requests:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: SPRING_CLOUD_SCHEDULER_KUBERNETES_NAMESPACE
              value: batch-ns
            - name: SPRING_PROFILES_ACTIVE
              value: 'private'
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_CONFIG_URI
              value: 'http://spring-config-server.svc.cluster.local:80'
            - name: SPRING_APPLICATION_NAME
              value: 'spring-cloud-dataflow-server-boot'
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              value: '{cipher}xxxxxxxxxxx'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED
              value: 'false'
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
              value: 'false'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: 'false'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
              value: /etc/secrets
            - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
              value: 'http://${SCDF_SERVER_SERVICE_HOST}:${SCDF_SERVER_SERVICE_PORT}'
              # Add Maven repo for metadata artifact resolution for all stream apps
            - name: SPRING_APPLICATION_JSON
              value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"
          envFrom:
            - secretRef:
                name: spring-config-server
      serviceAccountName: scdf-sa
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Warsaw
```

App configuration:

```
server:
  port: 9393
logging:
  level:
    root: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.cloud.task: info
    org.springframework.cloud.dataflow: info
    org.springframework.cloud.deployer.spi.kubernetes: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
spring:
  batch:
    initialize-schema: never
  datasource:
    url: jdbc:postgresql://xxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxx
    password: '{cipher}xxxxxxxx'
    driverClassName: org.postgresql.Driver
    testOnBorrow: true
    validationQuery: "SELECT 1"
  cloud:
    task:
      initialize-enabled: false
    dataflow:
      task:
        composedtaskrunner:
          uri: 'docker://eu.gcr.io/xxxxxxxx/spring-cloud-dataflow-composed-task-runner:2.7.1'
          use-user-access-token: true
        platform:
          kubernetes:
            accounts:
              default:
                namespace: batch-ns
                secretRefs:
                  - spring-config-server
                limits:
                  memory: 1024Mi
                environmentVariables:
                  JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Warsaw,
                  SPRING_CLOUD_CONFIG_URI=http://xxxxxxxxxxxx.svc.cluster.local:80,
                  SPRING_PROFILES_ACTIVE=production,
                  spring.cloud.config.password={cipher}xxxxxxxxxxxxxxxxxx
                imagePullPolicy: Always
```


I have noticed if I pass DB credential in kubernetes secret it's working and Composed Task can get DB credential without store it in database. 


```
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                namespace: batch-ns
                secretRefs:
                  - postgresql
```
