### ISSUE TITLE
Documentation: Using rest API via OpenShift through

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#4524]
**Problem description:**
Is your feature request related to a problem? Please provide a clear and concise description of what the problem is. 

**Solution description:**
Describe the solution you would like. We need a clear and concise description of what you want to happen. Also, have you considered cases outside the expected flow (edge cases)? What should happen in those cases?

**Description of alternatives:**
Describe alternatives you have considered: We need a clear and concise description of any alternative solutions or features you have considered.

**Additional context:**
Add any other context or explanation about the feature request here.

**Comment by klopfdreh** [comment]
Just wanted to know if there are any updates to update the documentation / on this ticket so far? I just had a look into the auto configuration of the client rest API (https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java) and found out 4 ways to configure the client:

**Basic Authentication**:
```yaml
spring:
  cloud:
    dataflow:
      client:
        authentication:
          basic:
            username: ...
            password: ...
```
**Client Credentials**:
```yaml
spring:
  cloud:
    dataflow:
      client:
        serverUri: https://hostname:8443
        authentication:
          client-id: clientid
          client-secret: secret
          token-uri: https://hostofoauth/oauth/token
          scope:
            - firstscope
            - anotherscope
```
**Access Token**:
```yaml
spring:
  cloud:
   dataflow:
     client:
       authentication:
         access-token: <token>
```
**Bearer Token**:
```yaml
spring:
  cloud:
   dataflow:
     client:
       authentication:
         oauth2:
           clientRegistrationId: clientid also used for client credentials mode
           username: <username> # User to authenticate with
           password: <password> # Password to authenticate with
```

Access Token and Bearer Token require the SCDF-Server to configure the resourceserver either with jwt or opaque token validation. (Docs can be found here: https://github.com/spring-projects/spring-security/blob/main/docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc)

My issue that there is no configuration for "client-authentication-method: post" is also still opened.

I just noticed that Spring Security did a recent update on this configuration (https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ClientAuthenticationMethod.java) - see "client_secret_post"

Thanks in advance :)
