### ISSUE TITLE
Application Properties not being loaded in Data Flow when image requires Kubernetes pull secret

### ISSUE THREAD

**Issue by fiidim** [spring-cloud/spring-cloud-dataflow#4734]
**Description:**
When using a private repository (i.e. GAR or GCR), that require authentication via a pull secret, application properties are not being displayed by data flow GUI.  The same application will display properties if configured with a non-pull secret proxy.  The typical error log message from data flow is:
`[nio-8080-exec-4] ApplicationConfigurationMetadataResolver : Failed to retrieve properties for resource Docker Resource [docker:northamerica-northeast1-docker.pkg.dev/<project>/<folder>/<application>-processor-kafka:<version>] because of ContainerRegistryException: Could not find an Registry Configuration for: northamerica-northeast1-docker.pkg.dev`

Skipper is able to pull the image when using the below, and the application and stream deploy ok as well.
`spring.cloud.skipper.server.platform.kubernetes.accounts.default.imagePullSecret: <my-pull-secret>`

I've tried variations of using `spring.cloud.dataflow.container.registry-configurations`, but they don't seem to support a pull secret, or provided no success.  The below doesn't seem to work for the pull secret either:
`
spring.cloud.dataflow.container.registry-configurations[artifactregistry].registry-host=northamerica-northeast1-docker.pkg.dev
spring.cloud.dataflow.container.registry-configurations[artifact-registry].user=_json_key
spring.cloud.dataflow.container.registry-configurations[artifact-registry].secret=<my-pull-secret>
spring.cloud.dataflow.container.registry-configurations[artifact-registry].authorizationType=dockeroauth2
`

Skipper reports this upon a successful pull:
`
[eTaskExecutor-3] o.s.c.d.s.k.KubernetesAppDeployer        : Preparing to run a container from  Docker Resource [docker:northamerica-northeast1-docker.pkg.dev/<project>/<folder>/<application>-processor-kafka:<version>]. This may take some time if the image must be downloaded from a remote container registry.
[eTaskExecutor-3] o.s.c.d.s.k.DefaultContainerFactory      : Using Docker image: docker:northamerica-northeast1-docker.pkg.dev/<project>/<folder>/<application>-processor-kafka:<version>
`

Secret is created in expected fashion:
`
kubectl create secret docker-registry artifact-registry 
--namespace <namespace> 
--docker-server=https://northamerica-northeast1-docker.pkg.dev 
--docker-email=<email> \
--docker-username=_json_key \
--docker-password="$(cat <secretfile>.json)"
`

**Release versions:**
I'm currently using `2.8.3` version of data flow, and `2.7.2` of skipper.

**Comment by fiidim** [comment]
I tested the above solution and it works.  I think the more elegant and consistent solution would be to implement `spring.cloud.dataflow.server.platform.kubernetes.accounts.default.imagePullSecret: <my-pull-secret>` rather to rely on an undocumented feature.

**Comment by corneil** [comment]
I usually update the skipper config yaml with:
```
    spring:
      cloud:
        deployer:
          kubernetes:
            imagePullPolicy: IfNotPresent
            imagePullSecret:
              -name: registry-key
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: IfNotPresent
                    imagePullSecret:
                      -name: registry-key
```
