### ISSUE TITLE
fail to define an openshift cloud provider on dataflow using login password

### ISSUE THREAD

**Issue by demetthyl** [spring-cloud/spring-cloud-dataflow#4746]
Hi,

i am trying to make a local installation with 2 modes : local + Kubernetes (OCP 3 and 4)

Here is my yaml configuration :

```
spring:
  cloud:
    dataflow:
      task:
        platform:
          local:
            accounts:
              localDev:
                shutdownTimeout: 60
                javaOpts: "-Dtest=foo -Xmx1024m"
              localDevDebug:
                javaOpts: "-Xdebug -Xmx2048m"
          kubernetes:
            accounts:
              default:
                deploymentServiceAccountName: myserviceaccountname
                fabric8:
                  master-url: https://host:443
                  username: xxxx
                  password: 1zzzz
                  namespace: ns
                limits:
                  cpu: 500m
                  memory: 1024Mi
                readinessProbeDelay: 120
                livenessProbeDelay: 90
                podSecurityContext:
                  runAsUser: 1000470000
```

It always fails with the issue :
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://host/api/v1/namespaces/ns/pods/ocp-task-vk42870ynw. Message: pods "ocp-task-vk42870ynw" is forbidden: User "system:anonymous" cannot get pods in the namespace

Then i tried the java approach to isolate the issue:

```````
Config config = new ConfigBuilder()
                .withMasterUrl("https://host:443")
//                .withOauthToken("LKFDJFKLDJFLDFvv88dfqd")
                .withUsername("xxx")
                .withPassword("zzzz")
                .withNamespace("ns")
                .withTrustCerts(true)
                .build();
        KubernetesClient client = new DefaultKubernetesClient(config);
        MixedOperation<Secret, SecretList, DoneableSecret, Resource<Secret, DoneableSecret>> secrets = client.secrets();
        System.out.println(secrets.list().toString());
```````

This fails with the same issue, using username + password
This WORKS using oauthToken

Then, if i switch DefaultKubernetesClientto DefaultOpenShiftClient as implementation, it works with username + password

How can i specify in my yaml to use the DefaultOpenShiftClient for my tasks platform bootstrap?

Or maybe i did it wrong: can you give me the best approach to define dual platform (local + ocp) for a local installation dataflow server?

Thanks,
Guillaume
