### ISSUE TITLE
Carvel monitoring features fail with airgapped repo

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4769]
When installing package with:
```
scdf:
  server:
    service:
      type: NodePort
  feature:
    monitoring:
      prometheus:
        enabled: true
      grafana:
        enabled: true
      prometheusRsocketProxy:
        enabled: true
```
There's some trouble in images like:
```
index.docker.io/springcloud/spring-cloud-dataflow-grafana-prometheus@sha256:123e227a390c0785dac7c12247ddb31eb3dd93f33e0888687c24f011fb417e0e
<airgapped>@sha256:cd93b8711bb92eb9c437d74217311519e0a93bc55779aa664325dc83cd13cb32
<airgapped>@sha256:8f18e1c37ce977c954e5fe3ef08a76f90190c3f2f88e3ad32b3a0e66ed531d15
```
Where `spring-cloud-dataflow-grafana-prometheus` should point to airgapped repo and as last two which are `prometheus` and `prometheus-rsocket-proxy` somewhat fails to pull image(which is mostly likely failure for repo auth).

Things work fine if deployed as is without airgapping as this airgapped repo was in purpose placed behind authentication.
