### ISSUE TITLE
Issue with MariaDB when using skipper-deployment.yaml

### ISSUE THREAD

**Issue by david-deck** [spring-cloud/spring-cloud-dataflow#4779]
The "skipper" database is automatically created by an initContainer defined in `src/kubernetes/skipper/skipper-deployment.yaml`.
```
      - name: init-mariadb-database
        image: mariadb:10.4.22
        env:
          - name: MARIADB_PWD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: mariadb-root-password
        command: ['sh', '-c', 'mariadb -h mariadb -u root --password=$MARIADB_PWD -e "CREATE DATABASE IF NOT EXISTS skipper;"']

```

There is no such initContainer for the mariadb/server database. Thus, Dataflow Server fails to start.
