### ISSUE TITLE
spring cloud dataflow launch task on other the kubernetes cluster

### ISSUE THREAD

**Issue by azmhyy2021** [spring-cloud/spring-cloud-dataflow#4830]
**Problem description:**

I want spring cloud dataflow launch task on  the the kubernetes cluster which is not running  the spring cloud dataflow server.
For example, spring cloud dataflow is running on AWS EKS and the task will be deployed and ran on Google GKE.

I can't find this feature

**Comment by cppwfs** [comment]
Hello @azmhyy2021 ,
SCDF supports the ability to launch an app in multiple platforms.     Here is the documentation on setting that up:
https://dataflow.spring.io/docs/recipes/multi-platform-deployment/multi-platform-task/#launching-tasks-across-multiple-platforms-from-an-external-spring-cloud-data-flow

**Comment by azmhyy2021** [comment]
> Hello @azmhyy2021 , SCDF supports the ability to launch an app in multiple platforms. Here is the documentation on setting that up: https://dataflow.spring.io/docs/recipes/multi-platform-deployment/multi-platform-task/#launching-tasks-across-multiple-platforms-from-an-external-spring-cloud-data-flow

In the manual, there is no explaination about how external kubernetes is configured.
no address no cluster name....

Could you explain it to me please?

**Comment by cppwfs** [comment]
I think this is a good addition to our microsite.   
Here is an example on setting up a masterUrl to a different K8's instance:
```
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                namespace: default
                limits:
                  memory: 1024Mi
              gpuzone:
                fabric8:
                  masterUrl: <k8s-master-api-url>
                  namespace: gpuzone-namespace
                  trustCerts: true
```
