### ISSUE TITLE
CTR arguments for child task are not passed when defined scheduler

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#5249]
Hi,

I have noticed some problem while defining schedule for CTR - when i.e. I have CTR:

![image](https://user-images.githubusercontent.com/57896357/223650824-fccba13d-51dc-48f7-8ace-ac875627c3f7.png)

When I launched manually it's work and arguments are passed:

![image](https://user-images.githubusercontent.com/57896357/223651179-0c973ef5-09cd-46a8-972b-9f13c8d3ac84.png)

In freetext view:
![image](https://user-images.githubusercontent.com/57896357/223652578-5c869329-1b66-4153-a523-b87459f181e9.png)

Below manifest from generated Jobs.yaml:

```
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: d9df7dae-5127-4302-bef9-6b66e8fbeda2
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: d9df7dae-5127-4302-bef9-6b66e8fbeda2
        job-name: ctr-task-test-task1-l5n7pyr0nn
        role: spring-app
        spring-app-id: ctr-task-test-task1-l5n7pyr0nn
        spring-deployment-id: ctr-task-test-task1-l5n7pyr0nn
        task-name: ctr-task-test-task1
    spec:
      containers:
      - args:
        - --management.metrics.tags.service=task-application
        - --spring.cloud.task.name=ctr-task-test-task1
        - --spring.datasource.url=jdbc:postgresql://xxx.xxx.xxx.xxx:5432/xxx?ssl=true&sslmode=verify-ca&sslrootcert=/etc/config/xxx.pem&sslcert=/etc/config/xxx.pem&sslkey=/etc/config/xxx.pk8
        - --spring.datasource.driverClassName=org.postgresql.Driver
        - --management.metrics.tags.application=${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}
        - task1-parm2=value2
        - task1-parm1=value1
        - --spring.cloud.task.parent-execution-id=9255
        - --spring.cloud.task.executionid=9257
        env:
```

And in logs this child task arguments are correct:

`08:41:48.042 [main] INFO org.springframework.batch.core.launch.support.SimpleJobLauncher - Job: [SimpleJob: [name=xxxxxxx]] launched with the following parameters: [{task1-parm1=value1, task1-parm2=value2, -spring.cloud.task.executionid=9257, -management.metrics.tags.service=task-application, -spring.profiles.active=xxxxxxx, -spring.cloud.task.external-execution-id=ctr-task-test-task1-l5n7pyr0nn, -spring.cloud.task.name=ctr-task-test-task1, pod-start-time=2023-03-08T08:41:09, -spring.datasource.driverClassName=org.postgresql.Driver, -spring.datasource.url=jdbc:postgresql://xxx.xxx.xxx.xxx:5432/xxx?ssl=true&sslmode=verify-ca&sslrootcert=/etc/config/xxx.pem&sslcert=/etc/config/xxx.pem&sslkey=/etc/config/xxx.pk8, -spring.kubernetes.pod.name=ctr-task-test-task1-l5n7pyr0nn-c5bt9, -spring.cloud.task.parent-execution-id=9255, run.id=41, -management.metrics.tags.application=${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}}]
`

BUT when I create schedule this CTR with the same arguments:

![image](https://user-images.githubusercontent.com/57896357/223652750-ad33246e-0226-4e59-ae39-04f76e574824.png)

The CronJob which is created has different arguments in compare to manual Jobs:
```

  failedJobsHistoryLimit: 30
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
          labels:
            spring-cronjob-id: ctr-task-test
        spec:
          containers:
          - args:
            - --management.metrics.tags.service=task-application
            - --spring.datasource.url=jdbc:postgresql://xxx.xxx.xxx.xxx:5432/xxx?ssl=true&sslmode=verify-ca&sslrootcert=/etc/config/xxx.pem&sslcert=/etc/config/xxx.pem&sslkey=/etc/config/xxx.pk8
            - --spring.datasource.driverClassName=org.postgresql.Driver
            - --management.metrics.tags.application=${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}
            - --dataflowServerUri=http://xxx.xxx.xxx.xxx
            - --spring.cloud.task.name=ctr-task-test
            - --graph=ctr-task-test-task1 && ctr-task-test-task2
            - app.task1.0=task1-parm1=value2
            - app.task1.1=task1-parm2=value2
            - app.task2.0=task2-parm1=hellotask2
            - app.task2.1=task2-parm2=worldtask2
            env:
```

And after run:

In logs child task my argument not exists:

`08:51:22.503 [main] INFO org.springframework.batch.core.launch.support.SimpleJobLauncher - Job: [SimpleJob: [name=xxxx]] launched with the following parameters: [{-spring.cloud.task.executionid=9262, -management.metrics.tags.service=task-application, -spring.profiles.active=xxxx, -spring.cloud.task.external-execution-id=ctr-task-test-task1-dqmnrl6wlo, -spring.cloud.task.name=ctr-task-test-task1, pod-start-time=2023-03-08T08:50:45, -spring.datasource.driverClassName=org.postgresql.Driver, -spring.datasource.url=jdbc:postgresql://xxx.xxx.xxx.xxx:5432/xxx?ssl=true&sslmode=verify-ca&sslrootcert=/etc/config/xxx.pem&sslcert=/etc/config/xxx.pem&sslkey=/etc/config/xxx.pk8, -spring.kubernetes.pod.name=ctr-task-test-task1-dqmnrl6wlo-68zss, -spring.cloud.task.parent-execution-id=9261, run.id=42, -management.metrics.tags.application=${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}}]`
