### ISSUE TITLE
Init Container not translated from k8s platform to task's pod

### ISSUE THREAD

**Issue by juanpablo-santos** [spring-cloud/spring-cloud-dataflow#5280]
**Description:**
Init containers defined at k8s platform level don't get propagated to applications running on that platform, they must be set via task properties

**Release versions:**
```json
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.10.2"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.10.2"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.3.2"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.10.2",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.10.2/spring-cloud-dataflow-shell-2.10.2.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.9.1",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.9.2",
      "javaVersion": "1.8.0_362",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.9",
      "springVersion": "5.3.25"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://XXXYYYZZZ:6443"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      },
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://XXXYYYZZZ:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}
```

**Custom apps:**
N/A

**Steps to reproduce:**
Define a platform that defines init-containers, such as:
```yaml
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              onp:
                fabric8:
                  clientCertData: "client-cert-data-here"
                  clientKeyData: "client-key-data-here"
                  masterUrl: "https://XXX.YYY:6443"
                  namespace: "scdf"
                  trustCerts: true
                imagePullPolicy: Always
                initContainer:
                  containerName: shared-dir
                  environmentVariables: SHARED_DIR=/shared-dir
                  commands: /tmp/init.sh
                  imageName: XXXX.YYYY:zzz
                  volumeMounts:
                    - name: vol-shared-dir
                      mountPath: "/shared-dir"
                      readOnly: false
                namespace: "scdf"
                volumes:
                  - name: "vol-shared-dir"
                volumeMounts:
                  - name: "vol-shared-dir"
                    mountPath: "/shared-dir"
                    readOnly: false
```

When running any task on that platform, you'll see that, by default, every parameter (env vars, volumes, volume mounts, pull policy, fabric8 connection details, etc) in the above configuration is built into the pod, except the init-containers. We have to manually pass them as task properties, something along the lines of:
```
spring.cloud.dataflow.task.platformName=onp
deployer.<TASK_ID>.kubernetes.init-container.container-name=shared-dir
deployer.<TASK_ID>.kubernetes.init-container.environment-variables=SHARED_DIR=/shared-dir
deployer.<TASK_ID>.kubernetes.init-container.commands=/tmp/init.sh
deployer.<TASK_ID>.kubernetes.init-container.image-name=XXXX.YYYY:zzz
deployer.<TASK_ID>.kubernetes.init-container.volume-mounts=[{name: 'vol-shared-dir', mountPath: '/shared-dir', readOnly: false}]
```

We've also tried setting the properties using the `spring.cloud.deployer.kubernetes` namespace, and IIRC, `deployer.kubernetes`, but that didn't make a difference.

This happens setting up the server either as a local standalone jar, or through the helm chart.

**Screenshots:**
N/A

**Additional context:**
N/A
