### ISSUE TITLE
Spring Cloud Data Flow Server Prometheus metrics are not showing the correct values

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5357]
**Description:**
Currently there is an issue with the Prometheus metrics of SCDF server. For example `http_server_requests_seconds_max` of any path is showing the value 0.0 even if I navigate through the UI. 

**Release versions:**
2.10.3

**Custom apps:**
-

**Steps to reproduce:**
Setup `spring-cloud-dataflow-server` with `prometheus-rsocket-proxy` and see `/metrics/connected` endpoint.

**Screenshots:**
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/980773/3a6cf4ee-a9da-4ec6-a687-e4a774efe109)

Note: We created our own artifact. based on `https://github.com/spring-cloud/spring-cloud-dataflow/tree/v2.10.3/spring-cloud-dataflow-server` That is the reason why there is a 1.0.63 mentioned.

**Additional context:**
The metrics are provided, but the count somehow is not working

**Comment by klopfdreh** [comment]
I got the dasbhoard from here: https://grafana.com/grafana/dashboards/9933-streams/ and this might be changed so that the application is check that it starts with a pattern so that you can name the application with `myservername-1` and `myservername-2` or `myservername-randomidentifier`

**Comment by klopfdreh** [comment]
The dashboard should be adjusted so that it use `=~` in the metrics.

Variable Value: `SERVER_APPLICATION_NAME=myservername.*` (the `.*` is important to match all pods)
Env-Variable: `MY_POD_NAME` = myservername-3h35f2t3d-rcg8d

Example:
```
"expr": "process_uptime_seconds{application=~\"${SERVER_APPLICATION_NAME}\"}",
```

application.yml
```yml
management:
  metrics:
    tags:
      application: ${MY_POD_NAME}
```

SCDF deployment `env`-variables:
```yml
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
```
