### ISSUE TITLE
spring-cloud-deployer-local.java-opts for Local usage.

### ISSUE THREAD

**Issue by evakule** [spring-cloud/spring-cloud-dataflow#5527]
I need somehow to paste configuration for java-opts before my app launches by default:
`task create some-task --definition "some-app" --spring-cloud-deployer-local.java-opts "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED" 
`
Each time I'm launching my task java-opts will automatically injects into my java -jar command. Now each time you launching task from UI you need to click EDIT button and paste properties into java-opts section. Same for shell.

**Comment by onobc** [comment]
Hi @evakule ,

You can not set the deployment properties on the task definition but you can set them as platform properties per environment. See [here](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-local-tasks) for details but **TL;DR** is if you add something like this to your app config:

```yaml
spring:
  cloud:
    dataflow:
      task:
        platform:
          local:
            accounts:
              default:
                javaOpts: "--add-opens java.base/sun.nio.ch=ALL-UNNAMED"
```
You will see this when you launch your tasks:
```
2023-11-02 18:59:54.065  INFO 36609 --- [nio-9393-exec-1] o.s.c.d.spi.local.LocalTaskLauncher      : Command to be executed: /Users/cbono/.sdkman/candidates/java/19.0.2-amzn/bin/java --add-opens java.base/sun.nio.ch=ALL-UNNAMED -jar /Users/cbono/.m2/repository/io/spring/timestamp-task/2.0.2/timestamp-task-2.0.2.jar --app.timestamp.spring.cloud.task.initialize-enabled=false --app.timestamp.spring.batch.jdbc.table-prefix=BATCH_ --app.timestamp.spring.cloud.task.tablePrefix=TASK_ --app.timestamp.spring.cloud.task.schemaTarget=boot2 --app.timestamp.spring.cloud.deployer.bootVersion=2 --spring.cloud.task.executionid=1
2023-11-02 18:59:54.080  INFO 36609 --- [nio-9393-exec-1] o.s.c.d.spi.local.LocalTaskLauncher      : launching task dd-09781bd9-285d-45d2-855b-5eb0b7480921
```
