### ISSUE TITLE
Scdf forbids to launch the same task on two different platforms

### ISSUE THREAD

**Issue by damthemad** [spring-cloud/spring-cloud-dataflow#5542]
**Description:**
I'm not sure if this is a bug or feature.  
For me it sounds like a bug, but there is a specific exception with a specific message which shows that this is intentional

When you try to run the same task on two differents platforms (using spring.cloud.dataflow.task.platformName property), scdf throws an exception (IllegalStateException), and a 500 http error code api response, with a message that explains that this is not possible (see screenshot).

**Release versions:**
2.10.3

**Steps to reproduce:**
Declare two platforms in scdf
```yaml
          task:
            platform:
              kubernetes:
                accounts:
                  platform1:
                    namespace: "xxx"
                    imagePullPolicy: "xxx"
                    imagePullSecret: "xxx"

                  platform2:
                    namespace: "yyy"
                    imagePullPolicy: "yyy"
                    imagePullSecret: "yyy"

```

Launch one task on the first platform (via ihm). for eg test-task. on platform1
Try to launch the same task on the second platform, platform2

**Screenshots:**
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/5691315/87f57c84-7382-41a2-a2c2-bee56056b950)

**Additional context:**
i can see that scdf reads table TASK_DEPLOYMENT and blocks if there is a line with TASK_DEFINITION_NAME = "test-task" and PLATFORM_NAME = "platform1".
