### ISSUE TITLE
SCDF 2.11.2 No AuthenticationProvider found

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5641]
**Description:**
When I used SCDF 2.11.2 and try to login an error occurs:

An authentication failure event occurred while accessing a REST resource that requires authentication.","context":"default","exception":"org.springframework.security.authentication.ProviderNotFoundException: No AuthenticationProvider found for org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationToken

**Release versions:**
Release 2.11.2 - I cant provide the JSON because I cant login.

**Custom apps:**
N/A

**Steps to reproduce:**
Simply setup SCDF with OAuth

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by klopfdreh** [comment]
This is our OAuth2 Config
```yml
    spring:
      security:
        oauth2:
          resourceserver:
            opaquetoken:
              introspection-uri: <<introspect_URI>>
              client-id: <<clientId_program_login>>
              client-secret: <<clientSecret_program_login>>
          client:
            registration:
              user_login:
                provider: user_login
                client-id: <<clientId>>
                client-secret: <<clientSecret>>
                client-authentication-method: client_secret_post
                redirect-uri: <<redirect_URI>>
                authorization-grant-type: authorization_code
                scope:
                  - <<scope1>>
                  - <<scope2>>
                  - <<scope3>>
                  - <<scope4>>
                  - <<scope5>>
                  - <<scope6>>
                  - <<scope7>>
              program_login:
                provider: program_login
                client-id: <<clientId_program_login>>
                client-secret: <<clientSecret_program_login>>
                authorization-grant-type: client_credentials
                scope:
                  - <<scope1>>
                  - <<scope2>>
                  - <<scope3>>
                  - <<scope4>>
                  - <<scope5>>
                  - <<scope6>>
                  - <<scope7>>
            provider:
              user_login:
                token-uri: <<token_uri>>
                user-info-uri: <<user_info_uri>>
                user-name-attribute: email
                authorization-uri: <<authorization_uri>>
              program_login:
                token-uri: <<token_uri>>
```
