### ISSUE TITLE
Access Denied on Default MariaDB with 'root'@'localhost'

### ISSUE THREAD

**Issue by devFallingstar** [spring-cloud/spring-cloud-dataflow#5752]
**Description:**
I'm trying to build SCDF on Kubernetes with below values.yaml. While initializing MariaDB, it shows shutdown log after Warning log `Access denied for user 'root'@'localhost' (using password: YES)` (Uploaded on Screenshots)

```yaml
spring-cloud-dataflow:
  server:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    replicaCount: 3
    ingress:
      enabled: true
      hostname: #### Masking
  skipper:
    replicaCount: 3
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
  mariadb:
    enabled: true
  rabbitmq:
    enabled: false
  kafka:
    enabled: true
```

**Release versions:**
SCDF : 26.0.0
Kubenetes : 1.27.5

**Custom apps:**
N/A

**Steps to reproduce:**
1. Create custom helm chart with below Chart.yaml and values.yaml
```yaml
## Chart.yaml
apiVersion: v2
name: scdf-helm-charts
description: A Helm chart for SCDF (Spring Cloud Dataflow)

maintainers:
  - name: Yousung Yang

type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: spring-cloud-dataflow
    version: 26.0.0
    repository: https://charts.bitnami.com/bitnami
```
```yaml
```yaml
### values.yaml
spring-cloud-dataflow:
  server:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    replicaCount: 3
    ingress:
      enabled: true
      hostname: #### Masking
  skipper:
    replicaCount: 3
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
  mariadb:
    enabled: true
  rabbitmq:
    enabled: false
  kafka:
    enabled: true
```
2. Run helm command `helm upgrade --install scdf . --namespace scdf --values values-dev.yaml --debug`

**Screenshots:**
<img width="808" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/23091621/6d0611b1-0119-46a1-b0a6-e799cf655c81">
