### ISSUE TITLE
Request to consider adding ownerreferences to subtasks created by composed task as well

### ISSUE THREAD

**Issue by wqld** [spring-cloud/spring-cloud-dataflow#5767]
**Problem description:**

CronJob resources deployed to Kubernetes environments by Spring Cloud Dataflow have a `successfulJobsHistoryLimit` value of 3 by default.
By this setting, the maximum number of Task Pods created from a CronJob is three (Completed).

However, Sub Task Pods created from `Composed Task` may have problems with IP assignment, Max Pod count limit, etc. because they are in a situation where more than 3 Completed pods are maintained.

**Solution description:**

This is caused by the lack of an `Ownerreferences` setting.
Task Pods that are created from the flow CronJob -> Job -> Pod have `Ownerreferences` as normal. As a result, when the Job is deleted, the Task Pods are also cleaned up by the GC.

```yaml
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: test-statistics-daily-28543710
    uid: 8f2f58f3-7e68-48c6-bbc6-b9a5435117e5
```

However, Sub task pods that are additionally created by Composed Tasks are not automatically cleaned up because they do not have `Ownerrefences`.
This causes various issues and should be fixed so that Sub task pods are given the same `Ownerreferences`.

**Additional context:**

- kubernetes: 1.28.6-eks
- batch/v1 CronJob
- spring-cloud-dataflow: 2.11.2
- composed-task-runner: 2.11.2
