### ISSUE TITLE
Question: How can i access Pod Metadata when i launch a Task using Dashboard

### ISSUE THREAD

**Issue by PPakSang** [spring-cloud/spring-cloud-dataflow#5769]
Hi, we're currently using SCDF 2.8.4

we're trying to launch a Task with init-container, and I couldn't find how to use kubernetes metadata like POD_ID to launch Task

i just write platform-properties such like below
`deployer.demo-task.kubernetes.initContainer={containerName: 'test', imageName: 'ppaksang/test', commands: ['test'], environment-variables: ['POD_IP=status.podIP']}`

plus, i don't know why init-container configuration didn't work even though i apply it while deploying dataflow server like below

```yaml
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default:
                init-container:
                  container-name: "test"
                  image-name: "ppaksang/test"
                  commands: ['test']
                  environment-variables: ['POD_IP=status.podIP']
```
