### ISSUE TITLE
Issue with Maximum Number of Accounts under task.platform.cloudfoundry.accounts

### ISSUE THREAD

**Issue by DanFrei** [spring-cloud/spring-cloud-dataflow#5932]
**Description:**
 Problem: Issue with Maximum Number of Accounts under: "task.platform.cloudfoundry.accounts"
 We use SCDF for managing tasks and  we're experiencing an issue with Spring Cloud Data Flow where adding more than 23 entries under "task.platform.cloudfoundry".
 When adding more than 23 account,  the newly added accounts/platforms would not be added (do not appear in the UI nor retrieved by the API).
 We couldn't find any hard limitation for the amount of acconts in the documentation.
 
Further details:

Current Configuration: I have configured 27 accounts under task.platform.cloudfoundry.accounts.
Problem: Only 23 accounts appear in the Spring Cloud Data Flow UI. The remaining accounts are not displayed, nor are they accessible.
Impact: We manage many Cloud Foundry accounts and need all of them available for our Spring Cloud Data Flow server. This limitation is blocking us from running tasks on certain accounts.
 
 
Request:

Could you please confirm if there is a hard limit on the number of entries allowed under "task.platform.cloudfoundry.accounts"?
If such a limit exists, is there a way to increase the allowed number of accounts via configuration, or would a code fix be necessary to support a larger number of accounts?
Any guidance or workaround for this issue would be appreciated. 

**Release versions:**
Spring Cloud Data Flow version: 2.11.3
Environment: Cloud Foundry

Example manifest yml to explain how we configure the accounts:

```
`spring-application-yaml:
 .
 .
 .
  spring.cloud.dataflow:
    task.platform.cloudfoundry.accounts:
      default:
        connection:
          url: (( .context.imports.cf.cc.srv_api_uri ))
          org: (( .context.product_config.uas_org "%UAS_DEV_SUFFIX%" ))
          space: (( .context.product_config.uas_space "%UAS_DEV_SUFFIX%" ))
          domain: (( .context.imports.cf.deprecated.app_domain ))
          username: CF_DATA_FLOW_USER
          password: ${vcap.services.uas-scdf-user-credentials.credentials.uas_dataflow_password.password}
          loginHint: (( .context.config.scdf_login_hint || "%7B%22origin%22%3A%22uaa%22%7D" ))
          skipSsValidation: false
        deployment:
          services: uas_credentials, uas-data-flow-server, uas-dataflow-postgres %OPTIONAL_BOUND_SERVICES%
          apiTimeout: 1200
          buildpacks: java_buildpack
     account-1:
        connection:
          url: (( .context.imports.cf.cc.srv_api_uri ))
          org: (( .context.product_config.uas_org "%UAS_DEV_SUFFIX%" ))
          space: (( .context.product_config.uas_space "%UAS_DEV_SUFFIX%" ))
          domain: (( .context.imports.cf.deprecated.app_domain ))
          username: CF_DATA_FLOW_USER
          password: ${vcap.services.uas-scdf-user-credentials.credentials.uas_dataflow_password.password}
          loginHint: (( .context.config.scdf_login_hint || "%7B%22origin%22%3A%22uaa%22%7D" ))
          skipSsValidation: false
        deployment:
          services: uas_credentials, uas-data-flow-server, uas-dataflow-postgres %OPTIONAL_BOUND_SERVICES%
          apiTimeout: 1200
          buildpacks: java_buildpack   
     account-2:
        connection:
          url: (( .context.imports.cf.cc.srv_api_uri ))
          org: (( .context.product_config.uas_org "%UAS_DEV_SUFFIX%" ))
          space: (( .context.product_config.uas_space "%UAS_DEV_SUFFIX%" ))
          domain: (( .context.imports.cf.deprecated.app_domain ))
          username: CF_DATA_FLOW_USER
          password: ${vcap.services.uas-scdf-user-credentials.credentials.uas_dataflow_password.password}
          loginHint: (( .context.config.scdf_login_hint || "%7B%22origin%22%3A%22uaa%22%7D" ))
          skipSsValidation: false
        deployment:
          services: uas_credentials, uas-data-flow-server, uas-dataflow-postgres %OPTIONAL_BOUND_SERVICES%
          apiTimeout: 1200
          buildpacks: java_buildpack  
          
          .
          .
          .
          .
          
   account-24:
        connection:
          url: (( .context.imports.cf.cc.srv_api_uri ))
          org: (( .context.product_config.uas_org "%UAS_DEV_SUFFIX%" ))
          space: (( .context.product_config.uas_space "%UAS_DEV_SUFFIX%" ))
          domain: (( .context.imports.cf.deprecated.app_domain ))
          username: CF_DATA_FLOW_USER
          password: ${vcap.services.uas-scdf-user-credentials.credentials.uas_dataflow_password.password}
          loginHint: (( .context.config.scdf_login_hint || "%7B%22origin%22%3A%22uaa%22%7D" ))
          skipSsValidation: false
        deployment:
          services: uas_credentials, uas-data-flow-server, uas-dataflow-postgres %OPTIONAL_BOUND_SERVICES%
          apiTimeout: 1200
          buildpacks: java_buildpack       
```    
            '
          
Thank you for your help!
Best regards,
Daniel Fridman,
daniel.friedman@sap.com
