### ISSUE TITLE
deploymentServiceAccountName property not applied to k8s cronjob

### ISSUE THREAD

**Issue by GangHun-Jo** [spring-cloud/spring-cloud-dataflow#5939]
**Description:**
I tried to set up the service account for cronjob through the deploymentServiceAccountName property on the Spring Cloud Data Flow server, but it doesn't seem to work well.

Related Guide Link : https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_deployment_service_account
  
  

**Release versions:**
2.11.4
  
  

**Steps to reproduce:**
Here's my `server-config.yaml`
```
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    deploymentServiceAccountName: {{ .scdf.sa }}
```

**Comment by cppwfs** [comment]
Can you provide us with some detail as to what doesn't work well?   
Are the cronjobs not being created?
What does the SCDF log report when you create the schedule?
Are. you deploying to Kubernetes or Cloud Foundry?

This information will assist us in helping you.   Thanks!

**Comment by GangHun-Jo** [comment]
@cppwfs @corneil 
Cronjob was created well, but service account of the cronjob was default, not {{ .scdf.sa }}.
There wasn't any log related to this bug.

Additionally I tried to add the property in @corneil 's comment, But It  work well neither

**Comment by corneil** [comment]
I made a mistake with the property:
```yaml
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    taskServiceAccountName: {{ .scdf.sa }}
```
Properties that fall under `spring.cloud.scheduler.kubernetes` should be added without the prefix.
