### ISSUE TITLE
Update InitContainers Docs

### ISSUE THREAD

**Issue by Wordbe** [spring-cloud/spring-cloud-dataflow#5945]
**Problem description**:
The options for initContainers described in the document https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_init_containers differ from the options used in regular Kubernetes pods. 
This discrepancy causes confusion for users who are familiar with standard pod syntax.  

**Solution description**:
We request an enhancement of the documentation. Please introduce and explain the various options available for initContainers in the document. Specifically, clarify the following options:
- containerName (not name)
- imageName (not image)
- environmentVariables (not env)

Additionally, it would be helpful to provide an example of how to use these options in a YAML file, such as:
```yaml
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    initContainers:
                      - containerName: test
                        imageName: busybox:latest
                        commands: 
                          - sh
                          - -c
                          - echo hello
                      - containerName: test2
                        imageName: busybox:latest
                        commands:
                          - sh
                          - -c
                          - echo world
```
Furthermore, please include information about other possible options, such as:
- imagePullPolicy
- volumeMounts
- and others
