### ISSUE TITLE
Provide server configuration to pass in env-vars/application properties to passed to all deployed application runtimes

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#661]
Something like
```
spring:
  cloud:
    dataflow:
      environmentVariables:
        SPRING_CLOUD_CONFIG_URI: http://localhost:8888
```
Would enable all apps deployed by the Data Flow server to have the config server uri set as an environment variable.
 
See https://github.com/spring-cloud/spring-cloud-deployer/issues/70
