### ISSUE TITLE
Verify health-check after disabling redis-store

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#857]
_From @channing-jackson on August 26, 2016 17:57_

Deployed 1.0.0.RC1 successfully, and checked /management/health endpoint and it shows down. 

Following are the entries in the manifest: 

```
applications: 
- name: mydataflow
  memory: 1024M
  disk_quota: 1024M
  no-route: false
  no-hostname: false
  health-check-type: 'port' 
  buildpack: custom_java_buildpack_offline
  env: 
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: https://api.dev.xyz.com
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: myorg
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: myspace
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: dev.xyz.com
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: dev-bde-rabbit,dev-bde-sccs
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: <user>
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: <password>
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_BUILDPACK: custom_java_buildpack_offline
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: false
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_APP_NAME_PREFIX: abc
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY: 768
    JAVA_OPTS: -Dhttp.keepAlive=false
    MAVEN_REMOTE_REPOSITORIES_SNAPSHOTS_URL: https://mavenrepo.xyz.com/nexus/content/repositories/snapshots/
    MAVEN_REMOTE_REPOSITORIES_RELEASES_URL: https://mavenrepo.xyz.com/nexus/content/repositories/releases/
    MAVEN_REMOTE_REPOSITORIES_SPRING_MILESTONES_URL: https://mavenrepo.xyz.com/nexus/content/repositories/spring-milestones/
    MAVEN_REMOTE_REPOSITORIES_SPRING_SNAPSHOTS_URL: https://mavenrepo.xyz.com/nexus/content/repositories/spring-snapshots/
    MAVEN_REMOTE_REPOSITORIES_SPRING_RELEASE_URL: https://mavenrepo.xyz.com/nexus/content/repositories/spring-release/
  services: 
    - dev-bde-rabbit
    - dev-bde-mysql
    - dev-bde-sccs
```
Application is not actually down.  It is running fine.

_Copied from original issue: spring-cloud/spring-cloud-dataflow-server-cloudfoundry#169_

**Comment by sabbyanandan** [comment]
@channing-jackson: This is a known behavior. Given that `spring-data-redis` is in the classpath, Boot tries to automatically connect to it. However, if we do not bind the server to redis, the health-check fails and the reason for the status. 

Unless you're using the analytic-store backed by any of the counter-sink's, this feature is unused anyway, so we are exploring options to disable the auto-configuration by default and allow end users to override it. 

Since this is observed across all dataflow-server implementations, I will move this to the core project.

**Comment by ilayaperumalg** [comment]
There is no way for us to control the `RedisAutoConfiguration` because we **always** enable `analytic` features by default which means the `redis` is expected to be **UP**

The status that is shown at the `/health` endpoint is the aggregated status which would show `DOWN` if at least one of the health endpoints shows as `DOWN`.

One option would be to disable analytics features by default and make the user explicitly `enable` if needed.

**Comment by channing-jackson** [comment]
Are there any properties or environment variables we might be able to set at deployment time that would disable the analytics feature?

**Comment by ilayaperumalg** [comment]
Yes, you can find the doc for this [here] (http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.RELEASE/reference/htmlsingle/#enable-disable-specific-features).

But this story still requires fix that disables `redis` health indicator if analytics feature is disabled.

**Comment by kimjuny** [comment]
I had tried to set `spring.cloud.dataflow.features.analytics-enabled: false` manually, redis health feature is still visible in `/health`

```
spring:
  cloud:
    dataflow:
      features:
        analytics-enabled: false
```

I'm using spring-cloud Dalston SR3
